language: csharp
solution: src
notifications:
  email:
    on_success: always
    on_failure: always
  slack: cgiwave6:1NqbLKzmuRjgH6YOBVndxtwR
mono: none
dotnet: 2.1
script:
  - dotnet restore
  - dotnet build
after-success:
  - /bin/bash ./deploy.sh