version: "3"
services: 
  consul: 
    image: consul
    restart: always
    networks: 
      - potentiometer-gateway-network
    ports:
      - 0.0.0.0:8500:8500
  gateway: 
    build: 
      context: ./src
    depends_on: 
      - consul
      - registrator
    networks: 
      - potentiometer-gateway-network
  registrator: 
    image: gliderlabs/registrator
    restart: always
    volumes: 
      - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
      - consul
    networks: 
      - potentiometer-gateway-network
    command: "-internal consul://localhost:8500"
networks:
  potentiometer-gateway-network:
    name: potentiometer-network

