FROM microsoft/dotnet
COPY . /app
WORKDIR /app
# RUN apt-get install iputils-ping
RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
# EXPOSE 80/tcp
RUN chmod +x ./entrypoint.sh
CMD /bin/bash ./entrypoint.sh